# Generated by Django 6.0.5 on 2026-05-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, max_length=512, unique=True)),
                ('category', models.CharField(choices=[('IIT', 'IIT'), ('NIT', 'NIT'), ('IIIT', 'IIIT'), ('Deemed', 'Deemed'), ('Other', 'Other')], default='Other', max_length=32)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('stream', models.CharField(blank=True, default='', max_length=64)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('placement_score', models.FloatField(blank=True, null=True)),
                ('academic_score', models.FloatField(blank=True, null=True)),
                ('infrastructure_score', models.FloatField(blank=True, null=True)),
                ('ug_fee', models.CharField(blank=True, default='', max_length=64)),
                ('pg_fee', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=512)),
                ('branch_canonical', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('degree', models.CharField(blank=True, default='', max_length=64)),
                ('fees_inr', models.BigIntegerField(blank=True, null=True)),
                ('avg_package_inr', models.BigIntegerField(blank=True, null=True)),
                ('placement_rate', models.FloatField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='counselling.college')),
            ],
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('round', models.PositiveSmallIntegerField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('quota', models.CharField(db_index=True, max_length=32)),
                ('gender', models.CharField(default='GENDER_NEUTRAL', max_length=32)),
                ('opening_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('closing_rank', models.PositiveIntegerField(db_index=True)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='counselling.program')),
            ],
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['branch_canonical'], name='counselling_branch__9e8c63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('college', 'program_name', 'branch_canonical')},
        ),
        migrations.AddIndex(
            model_name='cutoff',
            index=models.Index(fields=['year', 'category', 'quota', 'closing_rank'], name='counselling_year_c7c7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cutoff',
            index=models.Index(fields=['year', 'round', 'category', 'closing_rank'], name='counselling_year_631f55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cutoff',
            unique_together={('program', 'year', 'round', 'category', 'quota', 'gender')},
        ),
    ]
