# Generated by Django 6.0.5 on 2026-05-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
