# Generated by Django 6.0.5 on 2026-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0002_studentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoff',
            name='exam_type',
            field=models.CharField(db_index=True, default='JEE_MAIN', max_length=32),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='rank_type',
            field=models.CharField(db_index=True, default='JEE_MAIN_CRL', max_length=64),
        ),
        migrations.AddIndex(
            model_name='cutoff',
            index=models.Index(fields=['exam_type', 'rank_type', 'year', 'round', 'closing_rank'], name='counselling_exam_ty_0b3ae2_idx'),
        ),
    ]
