# Generated by Django 6.0.5 on 2026-05-24 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0003_cutoff_exam_type_cutoff_rank_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=32)),
                ('exam_type', models.CharField(default='JEE_MAIN', max_length=32)),
                ('rank_type', models.CharField(default='CRL', max_length=32)),
                ('gender', models.CharField(default='GENDER_NEUTRAL', max_length=32)),
                ('home_state', models.CharField(blank=True, default='', max_length=128)),
                ('branch_preferences', models.JSONField(blank=True, default=list)),
                ('year', models.PositiveSmallIntegerField()),
                ('round', models.CharField(default='LATEST', max_length=32)),
                ('results', models.JSONField(default=list)),
                ('trace', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
